### ISSUE TITLE
Filter session by type

### ISSUE THREAD

**Issue by ceci** [agile-alliance-brazil/submissions#186]
**As an...** author

**I want to...** filter submitted sessions by type

**In order to...** avoid submitting something that conflicts with another session by accident OR to know what sessions are my direct competitors.

**Comment by ericabriones** [comment]
Also as program chair I want to be able to follow up on new session types and give early feedback to authors that are using them, so I can increase the chances that those sessions can be approved and are delivering what we expected and/or are aligned with our expectation for them.

**Comment by hugocorbucci** [comment]
hmm.. what does 'follow up on session types' means?
Getting an email whenever there is a submission or update for that type? Having it as a 'saved search'? How would that look like? Is it an admin thing or can anyone do it?

**Comment by ericabriones** [comment]
I was thinking "low tech", but I was most certainly planning on weekly, during the submission period, entering the system and searching for the following session types: duel, are you sure of it? and be creative!, just to be sure that the submissions capture the right idea of what we want them to deliver. Personally, since we don't have so many people that can work on the issues, I rather build simple functionalities that serve multiple purposes than ones that are too specific.

**Comment by hugocorbucci** [comment]
Commits between 1837d5917ad9d10ef2fdc5808aba0fd4a6c434a3 and 1fc6680104ec3558a96dd26900c49b837bf7bb4b from @celsoMartins solved this issue. @ericabriones confirmed it was all good! :+1:
