### ISSUE TITLE
Chrome freezes when I try to open the Admin page

### ISSUE THREAD

**Issue by gmotta** [agile-alliance-brazil/submissions#257]
Something is preventing me to open the admin page.

[admin page](https://submissoes-staging.agilebrazil.com/conferences/2018/edit)

![screen shot 2018-03-15 at 17 32 27](https://user-images.githubusercontent.com/301142/37489664-1f370796-2877-11e8-9115-a0f22122deba.png)

**Comment by hugocorbucci** [comment]
Should've been fixed by https://github.com/agile-alliance-brazil/submissions/commit/957747bfa09404e0010bae21b51db9de94fc0f64.

The problem was that the tagcloud couldn't render any words in the space given because the div was too small. Changed the body of the page to be:
```
div(tagcloud){width: 700px;height: 300px}. &nbsp;
```

This ensured the words can actually fit in the container and jqcloud finished running.
The commit just ensures that if we just have `div(tagcloud)` it won't infinite loop again.
